apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SERVICE_NAME }}-secrets
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  {{- include "env.secrets" . | indent 2 }}
  ATP_CRYPTO_KEY: "{{ .Values.ATP_CRYPTO_KEY }}"
  ATP_CRYPTO_PRIVATE_KEY: "{{ .Values.ATP_CRYPTO_PRIVATE_KEY }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SERVICE_NAME }}-predeploy-secrets
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": {{ if not .Values.keepHookLogs }}hook-succeeded, {{ end }}before-hook-creation
type: Opaque
stringData:
  {{- include "env.deploy" . | indent 2 }}
